/**
 * Type definitions for the OpenAI Realtime speech-to-speech agent provider.
 *
 * @remarks
 * These types cover the subset of the OpenAI Realtime API (GA) used by
 * {@link OpenAIRealtimeAgent}: the user-facing configuration, the
 * client-facing event union, and loose shapes for the server events the
 * provider consumes. Both the GA event names (`response.output_audio.*`)
 * and the earlier preview names (`response.audio.*`) are handled.
 *
 * @packageDocumentation
 */

import type { BaseProviderConfig } from '../../../core/types/providers';

/**
 * Turn-detection configuration for the Realtime session.
 *
 * @remarks
 * Mirrors the wire format's `turn_detection` object. Pass `null` to
 * disable server-side VAD entirely (the agent will then never detect
 * end-of-turn on its own — only useful with manual response triggering).
 */
export interface RealtimeAgentTurnDetection {
  /** VAD flavor: amplitude-based (`'server_vad'`) or model-based (`'semantic_vad'`). */
  type: 'server_vad' | 'semantic_vad';

  /** `semantic_vad` only — how eagerly the model ends the user's turn. */
  eagerness?: 'low' | 'medium' | 'high' | 'auto';

  /** `server_vad` only — activation threshold (0–1). */
  threshold?: number;

  /** `server_vad` only — audio to include before detected speech, in ms. */
  prefixPaddingMs?: number;

  /** `server_vad` only — silence duration that ends the turn, in ms. */
  silenceDurationMs?: number;
}

/**
 * A function tool the Realtime agent can invoke.
 *
 * @remarks
 * Maps to the session's `tools` array on the wire (with `type: 'function'`
 * added automatically). When the model calls a tool, the provider invokes
 * {@link OpenAIRealtimeAgentConfig.onFunctionCall} and sends the result
 * back as a `function_call_output` item followed by `response.create`.
 */
export interface RealtimeAgentTool {
  /** Function name the model references when calling the tool. */
  name: string;

  /** Description provided to the model as context. */
  description?: string;

  /** JSON Schema for the function arguments. */
  parameters?: Record<string, unknown>;
}

/**
 * A function call requested by the Realtime agent.
 */
export interface RealtimeAgentFunctionCall {
  /** Call identifier used to correlate the result. */
  callId: string;

  /** Tool name matching a {@link RealtimeAgentTool.name}. */
  name: string;

  /** JSON-encoded arguments generated by the model. */
  arguments: string;
}

/**
 * Configuration for {@link OpenAIRealtimeAgent}.
 *
 * @remarks
 * Extends {@link BaseProviderConfig}, so `apiKey`, `proxyUrl`, `timeout`,
 * and `debug` are also available. In direct (browser) mode, authentication
 * uses OpenAI's documented WebSocket subprotocols
 * (`'realtime'` + `'openai-insecure-api-key.<KEY>'`); pass an async
 * `apiKey` factory returning an ephemeral client secret (minted server-side
 * via `POST /v1/realtime/client_secrets`) to avoid exposing a long-lived
 * key. In proxy mode the proxy injects an `Authorization: Bearer` header.
 *
 * @example
 * ```typescript
 * const agent = new OpenAIRealtimeAgent({
 *   proxyUrl: '/api/proxy/openai-realtime',
 *   model: 'gpt-realtime',
 *   voice: 'marin',
 *   instructions: 'You are a concise, friendly voice assistant.',
 * });
 * ```
 */
export interface OpenAIRealtimeAgentConfig extends BaseProviderConfig {
  /**
   * Realtime model ID.
   *
   * @defaultValue `'gpt-realtime'`
   */
  model?: string;

  /** System instructions defining the agent's persona and behaviour. */
  instructions?: string;

  /**
   * Output voice name (e.g. `'alloy'`, `'marin'`, `'cedar'`).
   *
   * @defaultValue `'alloy'`
   */
  voice?: string;

  /** Sampling temperature for response generation. */
  temperature?: number;

  /**
   * Model used to transcribe the user's input audio.
   *
   * @remarks
   * Input transcription is what drives the SDK's `transcription.*` events
   * and conversation history — it runs alongside the speech-to-speech
   * model.
   *
   * @defaultValue `'gpt-4o-mini-transcribe'`
   */
  transcriptionModel?: string;

  /** BCP-47 language hint for input transcription (e.g. `'en'`). */
  language?: string;

  /**
   * Turn-detection settings.
   *
   * @remarks
   * Defaults to `{ type: 'server_vad' }`. Pass `null` to disable VAD.
   */
  turnDetection?: RealtimeAgentTurnDetection | null;

  /** Function tools the agent can call. */
  tools?: RealtimeAgentTool[];

  /**
   * Handler invoked when the agent calls a function tool.
   *
   * @remarks
   * The returned content is sent back as a `function_call_output` item and
   * a new response is requested so the agent can speak the result.
   */
  onFunctionCall?: (call: RealtimeAgentFunctionCall) => Promise<{ content: string }>;

  /** OpenAI organization ID, sent as an auth subprotocol in direct mode. */
  organizationId?: string;

  /** OpenAI project ID, sent as an auth subprotocol in direct mode. */
  projectId?: string;

  /**
   * Extra fields merged into the `session.update` payload's `session`
   * object, after the fields derived from this config.
   *
   * @remarks
   * Escape hatch for Realtime session options this config does not model
   * (e.g. `max_output_tokens`, prompt caching options).
   */
  sessionOverrides?: Record<string, unknown>;
}

/**
 * Loose shape for server events consumed by the provider.
 *
 * @remarks
 * The Realtime API has a large event surface; this type keeps the fields
 * the provider reads and leaves the rest untyped.
 *
 * @internal
 */
export interface RealtimeServerEvent {
  type: string;
  event_id?: string;
  item_id?: string;
  response_id?: string;
  delta?: string;
  transcript?: string;
  audio_start_ms?: number;
  audio_end_ms?: number;
  error?: { type?: string; code?: string; message?: string };
  item?: {
    id?: string;
    type?: string;
    call_id?: string;
    name?: string;
    arguments?: string;
  };
  response?: {
    id?: string;
    status?: string;
    output?: Array<{
      type?: string;
      call_id?: string;
      name?: string;
      arguments?: string;
    }>;
  };
}

/**
 * Discriminated union of events emitted by {@link OpenAIRealtimeAgent}
 * via `onAgentEvent`.
 *
 * @remarks
 * These are camelCase, client-friendly views of the raw Realtime server
 * events the provider considers interesting. Subscribe for UI state
 * (speaking indicators, live captions) beyond what the SDK-level events
 * provide.
 */
export type OpenAIRealtimeAgentEvent =
  | { type: 'user_started_speaking' }
  | { type: 'user_stopped_speaking' }
  | { type: 'conversation_text'; role: 'user' | 'assistant'; content: string }
  | { type: 'agent_transcript_delta'; delta: string }
  | { type: 'agent_audio_done' }
  | { type: 'function_call'; callId: string; name: string; arguments: string }
  | { type: 'error'; code?: string; message: string };
