/**
 * Type definitions for the ElevenLabs Conversational AI agent provider.
 *
 * @remarks
 * These types cover the subset of the ElevenLabs Conversational AI
 * WebSocket protocol (`/v1/convai/conversation`) used by
 * {@link ElevenLabsAgent}: the user-facing configuration, the
 * client-facing event union, and loose shapes for the server messages the
 * provider consumes.
 *
 * @packageDocumentation
 */

import type { BaseProviderConfig } from '../../../core/types/providers';

/**
 * A client tool call requested by the ElevenLabs agent.
 *
 * @remarks
 * Client tools are defined in the agent's dashboard configuration; when
 * the agent invokes one, the provider calls
 * {@link ElevenLabsAgentConfig.onClientToolCall} and sends the result back
 * as a `client_tool_result` message.
 */
export interface ElevenLabsClientToolCall {
  /** Call identifier used to correlate the result. */
  toolCallId: string;

  /** Tool name as configured in the agent dashboard. */
  toolName: string;

  /** Parsed parameters generated by the agent. */
  parameters: Record<string, unknown>;
}

/**
 * Configuration for {@link ElevenLabsAgent}.
 *
 * @remarks
 * Extends {@link BaseProviderConfig}, so `apiKey`, `proxyUrl`, `timeout`,
 * and `debug` are also available. Connection/authentication options, in
 * priority order:
 *
 * 1. **`signedUrl`** — a signed WebSocket URL (or async factory returning
 *    one) minted server-side via
 *    `GET /v1/convai/conversation/get-signed-url?agent_id=...`. The
 *    recommended flow for private agents in the browser.
 * 2. **`proxyUrl`** — route through the CompositeVoice proxy, which injects
 *    the `xi-api-key` header server-side.
 * 3. **`apiKey`** + `agentId` — direct connection with the key as a query
 *    parameter. Avoid in browsers with long-lived keys.
 * 4. **`agentId` alone** — public agents require no authentication.
 *
 * @example
 * ```typescript
 * const agent = new ElevenLabsAgent({
 *   agentId: 'agent_abc123',
 *   proxyUrl: '/api/proxy/elevenlabs',
 * });
 * ```
 */
export interface ElevenLabsAgentConfig extends BaseProviderConfig {
  /**
   * The Conversational AI agent ID (from the ElevenLabs dashboard).
   *
   * @remarks
   * Required unless {@link ElevenLabsAgentConfig.signedUrl} is provided.
   */
  agentId?: string;

  /**
   * A pre-signed WebSocket URL, or an async factory that returns one.
   *
   * @remarks
   * Signed URLs are short-lived; pass a factory so each `connect()` gets a
   * fresh one. When set, `agentId`, `apiKey`, and `proxyUrl` are ignored
   * for the connection itself.
   */
  signedUrl?: string | (() => Promise<string>);

  /**
   * Override the agent's system prompt for this conversation.
   *
   * @remarks
   * Sent in `conversation_initiation_client_data`. Overrides must be
   * enabled in the agent's security settings.
   */
  systemPrompt?: string;

  /** Override the agent's first message (spoken greeting). */
  firstMessage?: string;

  /** Override the agent's language (e.g. `'en'`, `'es'`). */
  language?: string;

  /** Override the agent's TTS voice ID. */
  voiceId?: string;

  /**
   * Dynamic variables substituted into the agent's prompt templates.
   *
   * @remarks
   * Sent as `dynamic_variables` in `conversation_initiation_client_data`.
   */
  dynamicVariables?: Record<string, string | number | boolean>;

  /**
   * Extra fields merged into the `conversation_initiation_client_data`
   * payload, after the fields derived from this config.
   *
   * @remarks
   * Escape hatch for initiation options this config does not model (e.g.
   * `custom_llm_extra_body`, extended override blocks).
   */
  initiationOverrides?: Record<string, unknown>;

  /**
   * Handler invoked when the agent calls a client tool.
   *
   * @remarks
   * The returned result is sent back as a `client_tool_result` message.
   * Throwing marks the result as an error.
   */
  onClientToolCall?: (call: ElevenLabsClientToolCall) => Promise<{ result: unknown }>;

  /**
   * Milliseconds of audio-event silence after which the agent's turn is
   * considered complete.
   *
   * @remarks
   * The ElevenLabs protocol has no explicit "audio done" message, so the
   * provider treats a gap in audio chunk arrival as the end of the agent's
   * turn (resolving the pipeline's `finalize()` wait).
   *
   * @defaultValue 1000
   */
  audioDoneSilenceMs?: number;
}

/**
 * Loose shape for server messages consumed by the provider.
 *
 * @internal
 */
export interface ElevenLabsServerMessage {
  type?: string;
  conversation_initiation_metadata_event?: {
    conversation_id?: string;
    agent_output_audio_format?: string;
    user_input_audio_format?: string;
  };
  user_transcription_event?: { user_transcript?: string };
  agent_response_event?: { agent_response?: string };
  agent_response_correction_event?: {
    original_agent_response?: string;
    corrected_agent_response?: string;
  };
  audio_event?: { audio_base_64?: string; event_id?: number };
  ping_event?: { event_id?: number; ping_ms?: number };
  interruption_event?: { reason?: string };
  vad_score_event?: { vad_score?: number };
  internal_tentative_agent_response_event?: { tentative_agent_response?: string };
  client_tool_call?: {
    tool_name?: string;
    tool_call_id?: string;
    parameters?: Record<string, unknown>;
  };
  error?: string;
}

/**
 * Discriminated union of events emitted by {@link ElevenLabsAgent}
 * via `onAgentEvent`.
 *
 * @remarks
 * Camelcase, client-friendly views of the raw Conversational AI server
 * messages the provider considers interesting. Subscribe for UI state
 * (VAD score meters, tentative responses, interruptions) beyond what the
 * SDK-level events provide.
 */
export type ElevenLabsAgentEvent =
  | { type: 'conversation_started'; conversationId: string }
  | { type: 'conversation_text'; role: 'user' | 'assistant'; content: string }
  | { type: 'tentative_agent_response'; content: string }
  | { type: 'agent_response_correction'; original: string; corrected: string }
  | { type: 'interrupted'; reason?: string }
  | { type: 'vad_score'; score: number }
  | { type: 'client_tool_call'; call: ElevenLabsClientToolCall }
  | { type: 'agent_audio_done' }
  | { type: 'error'; message: string };
