/**
 * Tests for the AWS event-stream codec and CRC32 implementation.
 *
 * Fixture bytes were generated with an independent reference encoder using
 * Node's zlib CRC32, so they validate the framing layout (prelude, header
 * encoding, CRC placement) against a second implementation — not just
 * against our own round-trip.
 */

// jsdom does not provide TextEncoder/TextDecoder — install Node's implementations.
import { TextEncoder, TextDecoder } from 'util';
global.TextEncoder = TextEncoder as unknown as typeof global.TextEncoder;
global.TextDecoder = TextDecoder as unknown as typeof global.TextDecoder;

import { crc32 } from '../../../../src/utils/aws/crc32';
import {
  encodeEventStreamMessage,
  decodeEventStreamMessage,
} from '../../../../src/utils/aws/eventstream';

/**
 * A complete AudioEvent frame with payload [1, 2, 3, 4], generated by an
 * independent reference encoder (Node zlib CRC32).
 */
// prettier-ignore
const AUDIO_EVENT_FIXTURE = new Uint8Array([
  0, 0, 0, 108, 0, 0, 0, 88, 92, 80, 156, 227, 13, 58, 109, 101, 115, 115, 97,
  103, 101, 45, 116, 121, 112, 101, 7, 0, 5, 101, 118, 101, 110, 116, 11, 58,
  101, 118, 101, 110, 116, 45, 116, 121, 112, 101, 7, 0, 10, 65, 117, 100, 105,
  111, 69, 118, 101, 110, 116, 13, 58, 99, 111, 110, 116, 101, 110, 116, 45,
  116, 121, 112, 101, 7, 0, 24, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111,
  110, 47, 111, 99, 116, 101, 116, 45, 115, 116, 114, 101, 97, 109, 1, 2, 3, 4,
  76, 103, 181, 14,
]);

/**
 * A complete TranscriptEvent frame with payload
 * `{"Transcript":{"Results":[]}}`, generated by the same reference encoder.
 */
// prettier-ignore
const TRANSCRIPT_EVENT_FIXTURE = new Uint8Array([
  0, 0, 0, 130, 0, 0, 0, 85, 181, 5, 153, 224, 13, 58, 109, 101, 115, 115, 97,
  103, 101, 45, 116, 121, 112, 101, 7, 0, 5, 101, 118, 101, 110, 116, 11, 58,
  101, 118, 101, 110, 116, 45, 116, 121, 112, 101, 7, 0, 15, 84, 114, 97, 110,
  115, 99, 114, 105, 112, 116, 69, 118, 101, 110, 116, 13, 58, 99, 111, 110,
  116, 101, 110, 116, 45, 116, 121, 112, 101, 7, 0, 16, 97, 112, 112, 108, 105,
  99, 97, 116, 105, 111, 110, 47, 106, 115, 111, 110, 123, 34, 84, 114, 97,
  110, 115, 99, 114, 105, 112, 116, 34, 58, 123, 34, 82, 101, 115, 117, 108,
  116, 115, 34, 58, 91, 93, 125, 125, 196, 167, 44, 146,
]);

describe('crc32', () => {
  it('should produce the standard check value for "123456789"', () => {
    expect(crc32(new TextEncoder().encode('123456789'))).toBe(0xcbf43926);
  });

  it('should match known values', () => {
    expect(crc32(new Uint8Array(0))).toBe(0);
    expect(crc32(new TextEncoder().encode('hello'))).toBe(0x3610a686);
  });

  it('should support incremental computation', () => {
    const whole = crc32(new TextEncoder().encode('123456789'));
    const partial = crc32(
      new TextEncoder().encode('456789'),
      crc32(new TextEncoder().encode('123'))
    );
    expect(partial).toBe(whole);
  });
});

describe('encodeEventStreamMessage', () => {
  it('should produce byte-identical AudioEvent frames to the reference encoder', () => {
    const frame = encodeEventStreamMessage(
      {
        ':message-type': 'event',
        ':event-type': 'AudioEvent',
        ':content-type': 'application/octet-stream',
      },
      new Uint8Array([1, 2, 3, 4])
    );

    expect(Array.from(frame)).toEqual(Array.from(AUDIO_EVENT_FIXTURE));
  });

  it('should produce byte-identical TranscriptEvent frames to the reference encoder', () => {
    const frame = encodeEventStreamMessage(
      {
        ':message-type': 'event',
        ':event-type': 'TranscriptEvent',
        ':content-type': 'application/json',
      },
      new TextEncoder().encode('{"Transcript":{"Results":[]}}')
    );

    expect(Array.from(frame)).toEqual(Array.from(TRANSCRIPT_EVENT_FIXTURE));
  });

  it('should encode empty payloads (end-of-stream AudioEvent)', () => {
    const frame = encodeEventStreamMessage({ ':event-type': 'AudioEvent' }, new Uint8Array(0));
    const decoded = decodeEventStreamMessage(frame);

    expect(decoded.payload.length).toBe(0);
    expect(decoded.headers[':event-type']).toBe('AudioEvent');
  });

  it('should reject oversized header names and values', () => {
    expect(() => encodeEventStreamMessage({ ['x'.repeat(256)]: 'v' }, new Uint8Array(0))).toThrow(
      'header name too long'
    );
    expect(() =>
      encodeEventStreamMessage({ name: 'v'.repeat(0x10000) }, new Uint8Array(0))
    ).toThrow('header value too long');
  });
});

describe('decodeEventStreamMessage', () => {
  it('should decode the AudioEvent fixture', () => {
    const message = decodeEventStreamMessage(AUDIO_EVENT_FIXTURE);

    expect(message.headers).toEqual({
      ':message-type': 'event',
      ':event-type': 'AudioEvent',
      ':content-type': 'application/octet-stream',
    });
    expect(Array.from(message.payload)).toEqual([1, 2, 3, 4]);
  });

  it('should decode from an ArrayBuffer (WebSocket binary frame)', () => {
    const buffer = TRANSCRIPT_EVENT_FIXTURE.slice().buffer;
    const message = decodeEventStreamMessage(buffer);

    expect(message.headers[':event-type']).toBe('TranscriptEvent');
    expect(JSON.parse(new TextDecoder().decode(message.payload))).toEqual({
      Transcript: { Results: [] },
    });
  });

  it('should round-trip encode/decode with a binary payload', () => {
    const payload = new Uint8Array(1024);
    for (let i = 0; i < payload.length; i++) payload[i] = i % 251;

    const headers = {
      ':message-type': 'event',
      ':event-type': 'AudioEvent',
      ':content-type': 'application/octet-stream',
    };
    const decoded = decodeEventStreamMessage(encodeEventStreamMessage(headers, payload));

    expect(decoded.headers).toEqual(headers);
    expect(Array.from(decoded.payload)).toEqual(Array.from(payload));
  });

  it('should reject frames with a corrupted prelude CRC', () => {
    const corrupted = AUDIO_EVENT_FIXTURE.slice();
    corrupted[9] = (corrupted[9] as number) ^ 0xff;
    expect(() => decodeEventStreamMessage(corrupted)).toThrow('prelude CRC mismatch');
  });

  it('should reject frames with a corrupted message CRC', () => {
    const corrupted = AUDIO_EVENT_FIXTURE.slice();
    // Flip a payload byte — prelude stays valid but the message CRC fails.
    corrupted[corrupted.length - 5] = (corrupted[corrupted.length - 5] as number) ^ 0xff;
    expect(() => decodeEventStreamMessage(corrupted)).toThrow('message CRC mismatch');
  });

  it('should reject truncated frames and length mismatches', () => {
    expect(() => decodeEventStreamMessage(new Uint8Array(4))).toThrow('too short');
    expect(() => decodeEventStreamMessage(AUDIO_EVENT_FIXTURE.subarray(0, 50))).toThrow(
      'length mismatch'
    );
  });

  it('should decode non-string header value types', () => {
    // Hand-built frame with one of each: boolean true, int32, and a string.
    const headerBytes: number[] = [];
    const pushName = (name: string): void => {
      headerBytes.push(name.length, ...Array.from(new TextEncoder().encode(name)));
    };
    pushName('bool');
    headerBytes.push(0); // type 0 = boolean true, no value bytes
    pushName('int');
    headerBytes.push(4, 0, 0, 1, 44); // type 4 = int32, value 300
    pushName('str');
    headerBytes.push(7, 0, 2, 104, 105); // type 7 = string, "hi"

    const totalLength = 12 + headerBytes.length + 4;
    const frame = new Uint8Array(totalLength);
    const view = new DataView(frame.buffer);
    view.setUint32(0, totalLength, false);
    view.setUint32(4, headerBytes.length, false);
    view.setUint32(8, crc32(frame.subarray(0, 8)), false);
    frame.set(headerBytes, 12);
    view.setUint32(totalLength - 4, crc32(frame.subarray(0, totalLength - 4)), false);

    const message = decodeEventStreamMessage(frame);
    expect(message.headers['bool']).toBe(true);
    expect(message.headers['int']).toBe(300);
    expect(message.headers['str']).toBe('hi');
    expect(message.payload.length).toBe(0);
  });

  it('should reject unknown header value types', () => {
    const headerBytes = [1, 120, 42]; // name "x", bogus type 42
    const totalLength = 12 + headerBytes.length + 4;
    const frame = new Uint8Array(totalLength);
    const view = new DataView(frame.buffer);
    view.setUint32(0, totalLength, false);
    view.setUint32(4, headerBytes.length, false);
    view.setUint32(8, crc32(frame.subarray(0, 8)), false);
    frame.set(headerBytes, 12);
    view.setUint32(totalLength - 4, crc32(frame.subarray(0, totalLength - 4)), false);

    expect(() => decodeEventStreamMessage(frame)).toThrow('Unknown event-stream header value type');
  });
});
