/**
 * Type definitions for the Gemini Live speech-to-speech agent provider.
 *
 * @remarks
 * These types cover the subset of the Gemini Live API (`BidiGenerateContent`
 * over WebSocket) used by {@link GeminiLiveAgent}: the user-facing
 * configuration, the client-facing event union, and loose shapes for the
 * server messages the provider consumes.
 *
 * @packageDocumentation
 */

import type { BaseProviderConfig } from '../../../core/types/providers';

/**
 * A function declaration the Gemini Live agent can invoke.
 *
 * @remarks
 * Maps to `tools[].functionDeclarations[]` in the setup message. When the
 * model calls a function, the provider invokes
 * {@link GeminiLiveAgentConfig.onFunctionCall} and sends the result back
 * in a `toolResponse` message.
 */
export interface GeminiLiveFunctionDeclaration {
  /** Function name the model references when calling. */
  name: string;

  /** Description provided to the model as context. */
  description?: string;

  /** OpenAPI-style schema for the function parameters. */
  parameters?: Record<string, unknown>;
}

/**
 * A function call requested by the Gemini Live agent.
 */
export interface GeminiLiveFunctionCall {
  /** Call identifier used to correlate the response. */
  id: string;

  /** Function name matching a {@link GeminiLiveFunctionDeclaration.name}. */
  name: string;

  /** Parsed arguments generated by the model. */
  args: Record<string, unknown>;
}

/**
 * Configuration for {@link GeminiLiveAgent}.
 *
 * @remarks
 * Extends {@link BaseProviderConfig}, so `apiKey`, `proxyUrl`, `timeout`,
 * and `debug` are also available. Direct (browser) mode authenticates via
 * the `key` query parameter on the WebSocket URL; in proxy mode the proxy
 * appends the key server-side so it never reaches the browser.
 *
 * @example
 * ```typescript
 * const agent = new GeminiLiveAgent({
 *   proxyUrl: '/api/proxy/gemini-live',
 *   model: 'gemini-2.0-flash-live-001',
 *   voice: 'Puck',
 *   systemInstruction: 'You are a concise, friendly voice assistant.',
 * });
 * ```
 */
export interface GeminiLiveAgentConfig extends BaseProviderConfig {
  /**
   * Live-capable model ID (e.g. `'gemini-2.0-flash-live-001'`,
   * `'gemini-2.5-flash-preview-native-audio-dialog'`).
   *
   * @defaultValue `'gemini-2.0-flash-live-001'`
   */
  model?: string;

  /** System instruction defining the agent's persona and behaviour. */
  systemInstruction?: string;

  /**
   * Prebuilt output voice name (e.g. `'Puck'`, `'Aoede'`, `'Charon'`).
   *
   * @remarks
   * Maps to `speechConfig.voiceConfig.prebuiltVoiceConfig.voiceName`.
   */
  voice?: string;

  /** BCP-47 language code for speech output (e.g. `'en-US'`). */
  language?: string;

  /** Sampling temperature for response generation. */
  temperature?: number;

  /**
   * Whether to request transcription of the user's input audio.
   *
   * @remarks
   * Input transcription is what drives the SDK's `transcription.*` events
   * and conversation history. Disable only if you do not need transcripts —
   * audio still flows either way.
   *
   * @defaultValue `true`
   */
  inputTranscription?: boolean;

  /**
   * Whether to request transcription of the agent's output audio.
   *
   * @remarks
   * Output transcription provides the assistant text for `llm.*` events
   * and conversation history.
   *
   * @defaultValue `true`
   */
  outputTranscription?: boolean;

  /** Function declarations the agent can call. */
  functionDeclarations?: GeminiLiveFunctionDeclaration[];

  /**
   * Handler invoked when the agent calls a function.
   *
   * @remarks
   * The returned response object is sent back in a `toolResponse` message.
   */
  onFunctionCall?: (call: GeminiLiveFunctionCall) => Promise<{ response: Record<string, unknown> }>;

  /**
   * Extra fields merged into the `setup` payload, after the fields derived
   * from this config.
   *
   * @remarks
   * Escape hatch for Live API setup options this config does not model
   * (e.g. `sessionResumption`, `contextWindowCompression`, `realtimeInputConfig`).
   */
  setupOverrides?: Record<string, unknown>;
}

/**
 * Loose shape for server messages consumed by the provider.
 *
 * @internal
 */
export interface GeminiServerMessage {
  setupComplete?: Record<string, unknown>;
  /**
   * Google API error envelope. The Live API may deliver this as a JSON
   * frame instead of (or before) a WebSocket close.
   */
  error?: {
    code?: number | string;
    message?: string;
    status?: string;
  };
  serverContent?: {
    modelTurn?: {
      parts?: Array<{
        inlineData?: { mimeType?: string; data?: string };
        text?: string;
      }>;
    };
    inputTranscription?: { text?: string };
    outputTranscription?: { text?: string };
    turnComplete?: boolean;
    generationComplete?: boolean;
    interrupted?: boolean;
  };
  toolCall?: {
    functionCalls?: Array<{
      id?: string;
      name?: string;
      args?: Record<string, unknown>;
    }>;
  };
  toolCallCancellation?: { ids?: string[] };
  goAway?: { timeLeft?: string };
  usageMetadata?: Record<string, unknown>;
}

/**
 * Discriminated union of events emitted by {@link GeminiLiveAgent}
 * via `onAgentEvent`.
 *
 * @remarks
 * Camelcase, client-friendly views of the raw Live API server messages the
 * provider considers interesting. Subscribe for UI state (interruptions,
 * session lifetime warnings) beyond what the SDK-level events provide.
 */
export type GeminiLiveAgentEvent =
  | { type: 'conversation_text'; role: 'user' | 'assistant'; content: string }
  | { type: 'interrupted' }
  | { type: 'turn_complete' }
  | { type: 'function_call'; calls: GeminiLiveFunctionCall[] }
  | { type: 'go_away'; timeLeft?: string }
  | { type: 'error'; message: string };
